# Generated by Django 6.0.6 on 2026-07-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='republicaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
