# Generated by Django 5.2.16 on 2026-07-16 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragmento_texto', models.CharField(max_length=500)),
                ('tipo_fragmento', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen')], default='texto', max_length=10)),
                ('contenido', models.CharField(max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='materiales.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anotacion',
                'verbose_name_plural': 'Anotaciones',
                'ordering': ['-creado'],
                'unique_together': {('usuario', 'libro', 'fragmento_texto')},
            },
        ),
    ]
