# Generated by Django 6.0.6 on 2026-07-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_libro_republicaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descargas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('retirado', 'Retirado')], default='borrador', max_length=20),
        ),
    ]
