# Generated by Django 5.2.16 on 2026-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_anotacion_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descargas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='visualizaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
