# Generated by Django 6.0.6 on 2026-07-16 15:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_libro_descargas_libro_visualizaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('visibilidad', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='publica', max_length=20)),
                ('limite_libros', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5, message='El límite mínimo de libros es 5')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='colecciones', to='materiales.categoria')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('libros', models.ManyToManyField(blank=True, related_name='colecciones_pertenecientes', to='materiales.libro')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.CreateModel(
            name='ParticipacionColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('participante', 'Participante')], default='participante', max_length=20)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='materiales.coleccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_coleccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participación en Colección',
                'verbose_name_plural': 'Participaciones en Colecciones',
                'unique_together': {('coleccion', 'usuario')},
            },
        ),
    ]
