# Generated by Django 6.0.6 on 2026-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_coleccion_participacioncoleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('retirado', 'Retirado')], default='borrador', max_length=20),
        ),
    ]
