# Generated by Django 6.0.6 on 2026-07-16 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0006_coleccion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='limite_libros',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5, message='El límite mínimo de libros es 5'), django.core.validators.MaxValueValidator(20, message='El límite máximo de libros es 20')]),
        ),
    ]
