# Generated by Django 6.0.6 on 2026-07-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_alter_coleccion_limite_libros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleccion',
            name='estado',
        ),
    ]
