# Generated by Django 6.0.6 on 2026-07-16 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0008_remove_coleccion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='limite_libros',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5, message='El mínimo es de 5 libros'), django.core.validators.MaxValueValidator(20, message='El máximo de libros es 20')]),
        ),
    ]
