# Generated by Django 5.2.16 on 2026-07-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_alter_coleccion_creador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacioncoleccion',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', max_length=20),
        ),
    ]
