# Generated by Django 6.0.6 on 2026-07-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_alter_coleccion_creador_and_more'),
        ('materiales', '0009_alter_coleccion_limite_libros'),
    ]

    operations = [
    ]
