# Generated by Django 6.0.6 on 2026-07-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_alter_coleccion_creador_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialColeccion',
        ),
    ]
