# Generated by Django 6.0.7 on 2026-07-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0010_participacioncoleccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacioncoleccion',
            name='indice_reputacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
