# Generated by Django 6.0.6 on 2026-07-16 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0010_merge_20260716_1538'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleccion',
            name='libros',
        ),
        migrations.CreateModel(
            name='LibroColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('agregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.coleccion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.libro')),
            ],
            options={
                'unique_together': {('coleccion', 'libro')},
            },
        ),
        migrations.AddField(
            model_name='coleccion',
            name='libros',
            field=models.ManyToManyField(blank=True, related_name='colecciones_pertenecientes', through='materiales.LibroColeccion', to='materiales.libro'),
        ),
    ]
