# Generated by Django 6.0.6 on 2026-07-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0011_librocoleccion'),
        ('materiales', '0011_participacioncoleccion_indice_reputacion'),
    ]

    operations = [
    ]
