# Generated by Django 6.0.6 on 2026-07-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0012_merge_20260716_2052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitacioncoleccion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='solicitudaccesocoleccion',
            unique_together=set(),
        ),
    ]
