# Generated by Django 6.0.6 on 2026-07-17 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0012_merge_20260716_2024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='BitacoraColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('agregar_libro', 'Agregar Libro'), ('quitar_libro', 'Quitar Libro'), ('ingreso_miembro', 'Ingreso Miembro'), ('salida_miembro', 'Salida Miembro'), ('cambio_configuracion', 'Cambio Configuración')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='materiales.coleccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Bitácora',
                'verbose_name_plural': 'Registros de Bitácora',
                'ordering': ['-fecha'],
            },
        ),
    ]
