# Generated by Django 6.0.6 on 2026-07-17 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0013_alter_invitacioncoleccion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('agregar_libro', 'Agregar libro'), ('quitar_libro', 'Quitar libro'), ('ingreso_miembro', 'Ingreso miembro'), ('salida_miembro', 'Salida miembro'), ('cambio_configuracion', 'Cambio configuración')], max_length=50)),
                ('detalles', models.CharField(blank=True, max_length=260, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='materiales.coleccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
