# Generated by Django 6.0.6 on 2026-07-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0013_alter_invitacioncoleccion_unique_together_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='bitacoracoleccion',
            name='detalles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoracoleccion',
            name='accion',
            field=models.CharField(choices=[('agregar_libro', 'Agregar libro'), ('quitar_libro', 'Quitar libro'), ('ingreso_miembro', 'Ingreso miembro'), ('salida_miembro', 'Salida miembro'), ('cambio_configuracion', 'Cambio configuración')], max_length=50),
        ),
    ]
