# Generated by Django 6.0.6 on 2026-07-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0013_alter_invitacioncoleccion_unique_together_and_more'),
    ]

    operations = []
