# Generated by Django 6.0.6 on 2026-07-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0012_merge_20260716_2024'),
        ('materiales', '0014_alter_invitacioncoleccion_unique_together_and_more'),
        ('materiales', '0014_bitacoracoleccion'),
    ]

    operations = [
    ]
