# Generated by Django 6.0.6 on 2026-07-17 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0015_merge_20260716_2114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacoracoleccion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Bitácora', 'verbose_name_plural': 'Registros de Bitácora'},
        ),
        migrations.CreateModel(
            name='ComentarioRetroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='materiales.coleccion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_coleccion', to='materiales.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_retroalimentacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Retroalimentación',
                'verbose_name_plural': 'Comentarios de Retroalimentación',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaCambioColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('inclusion', 'Inclusión'), ('exclusion', 'Exclusión')], max_length=20)),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_cambio', to='materiales.coleccion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_coleccion', to='materiales.libro')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
