# Generated by Django 6.0.6 on 2026-07-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0016_alter_bitacoracoleccion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoracoleccion',
            name='accion',
            field=models.CharField(choices=[('agregar_libro', 'Agregar libro'), ('quitar_libro', 'Quitar libro'), ('ingreso_miembro', 'Ingreso miembro'), ('salida_miembro', 'Salida miembro'), ('cambio_configuracion', 'Cambio configuración'), ('propuesta_enviada', 'Propuesta enviada'), ('propuesta_aprobada', 'Propuesta aprobada'), ('propuesta_rechazada', 'Propuesta rechazada')], max_length=50),
        ),
    ]
