# Generated by Django 6.0.6 on 2026-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='publicaciones', to='feed.categoria'),
        ),
    ]
