# Generated by Django 6.0.6 on 2026-07-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(default='info', max_length=50),
        ),
    ]
