# Generated by Django 6.0.6 on 2026-07-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_notificacion_extra_data_notificacion_tipo'),
        ('materiales', '0017_alter_bitacoracoleccion_accion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='publicaciones', to='materiales.categoria'),
        ),
    ]
