# Generated by Django 6.0.6 on 2026-07-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_delete_categoria_alter_publicacion_categorias'),
        ('materiales', '0017_alter_bitacoracoleccion_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='coleccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacion_feed', to='materiales.coleccion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='libro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacion_feed', to='materiales.libro'),
        ),
    ]
