# Generated by Django 6.0.6 on 2026-07-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_publicacion_coleccion_publicacion_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='titulo',
        ),
    ]
