# Generated by Django 6.0.6 on 2026-07-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cuota_descarga',
            field=models.IntegerField(default=500),
        ),
    ]
