# Generated by Django 6.0.6 on 2026-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_perfilusuario_cuota_descarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_ultima_renovacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
