# Generated by Django 6.0.6 on 2026-07-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_agregar_fecha_ultima_renovacion_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.CharField(default='avatar1.png', max_length=50),
        ),
    ]
