# Generated by Django 6.0.6 on 2026-07-16 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0003_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescarteRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descartes', to='feed.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descartes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarte de recomendacion',
                'verbose_name_plural': 'Descartes de recomendacion',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'publicacion'), name='descarte_unico_por_usuario_publicacion')],
            },
        ),
        migrations.CreateModel(
            name='HistorialLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='feed.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_lectura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de lectura',
                'verbose_name_plural': 'Historiales de lectura',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'publicacion'), name='lectura_unica_por_usuario_publicacion')],
            },
        ),
    ]
